name: package

on:
  push:
    branches: [master]

jobs:
    build-package:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
              python-version: 3.12
        - name: Check versions
          run: |
              pip install -U pip requests
              python3 .github/check_version.py -o
        - name: Build pip package
          run: |
              pip install -U pip build
              python3 -m build
        - name: Archive Pypi artifacts
          uses: actions/upload-artifact@v4
          with:
              name: pypi_dist
              path: dist
