services:
  app:
    build: .
    container_name: python-script
    command: uvicorn src.main:api --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - .:/code
    # depends_on:
    #   - redis

  # redis:
  #   image: redis:alpine
