#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
006_1_generate_code_ia_log_parser_csv_streamlit_pie_specific_humanized.py
source Python for GPT query  
QUERY :: Generate the code to select specific columns in a panda dataframe (df) in order to show it in a pie chart inside a Streamlit application 

CAUTION :: the code generated by Chat GPT slightly modified by human

"""


"""
[env]
# Conda Environment
conda create --name unstructured_data_python_parsing python=3.9.7
conda info --envs
source activate unstructured_data_python_parsing
conda deactivate
# if needed to remove
conda env remove -n [NAME_OF_THE_CONDA_ENVIRONMENT]

# update conda 
conda update -n base -c defaults conda


[path]
cd /Users/brunoflaven/Documents/03_git/BlogArticlesExamples/ai_chatgpt_usages/example_python



[file]
streamlit run 006_1_generate_code_ia_log_parser_csv_streamlit_pie_specific_humanized.py

# other module
pip install requests
pip install pandas
pip install streamlit
pip install numpy
pip install datetime
pip install watchdog

[source]
https://github.com/bflaven/BlogArticlesExamples/tree/master/unstructured_data_python_parsing

"""
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# df = pd.read_csv("data.csv")
df = pd.read_csv(
    "generate_code_ia_log_parser_panda_humanized_sample_error_data_humanized_2.csv")




# Select the specific columns
# columns = ["column1", "column2", "column3"]
columns = ["Num1", "Num1"]
# Date,Time,Num1,Num2,MsgType,Msg


selected_df = df[columns]

# Plot the pie chart
plt.pie(selected_df.sum(), labels=selected_df.columns)

# Show the plot in the Streamlit app
st.pyplot()


